board_touch:
  board_dimensions:
    width: 0.14
    length: 0.26
    height: 0.09
  clearance: 0.07
  force_threshold: 10

stiffness:
  K_pos: 1000
  K_z: 2000
  K_ori: 20

pose_box_ref_guess:
  trans_ref_guess: [0.47, 0.1500, 0.1]
  rot_ref_guess: [0.707, 0, 0, -0.707]

transform_cam:
  trans_cam: [0.62, 0.18, 0.575]
  rot_cam: [0.008, 0.735, -0.677, -0.014]

cartesian_pose_topic_name: '/cartesian_pose'
force_torque_ext_topic: '/force_torque_ext'
equilibrium_pose_topic: '/equilibrium_pose'
pose_ref_2_new_topic: '/pose_ref_2_new'
